apiVersion: v1
kind: Service
metadata:
  name: phpdemo
  namespace: phpdemo
spec:
  selector:
    app.kubernetes.io/name: phpdemo
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: ClusterIP

